Rolling Tavern/Models/BoardGame.cs
using Rolling_Tavern.Attributes;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Rolling_Tavern.Models
{
    public partial class BoardGame
    {
        public BoardGame()
        {
            Meetings = new HashSet<Meeting>();
        }

        public int GameId { get; set; }

        [Required(ErrorMessage = "Поле {0} є обов'язковим.")]
        [StringLength(32, ErrorMessage = "{0} повиннa бути не менше {2} та не більше {1} літер", MinimumLength = 2)]
        [Display(Name = "Назва гри")]
        public string GameName { get; set; }

        [Required(ErrorMessage = "Поле {0} є обов'язковим.")]
        [StringLength(18, ErrorMessage = "{0} повиннa бути не менше {2} та не більше {1} літер", MinimumLength = 4)]
        [Display(Name = "Жанр гри")]
        public string Genre { get; set; }

        [Required(ErrorMessage = "Поле {0} є обов'язковим.")]
        [StringLength(1000, ErrorMessage = "{0} повиннa бути не менше {2} та не більше {1} літер", MinimumLength = 1)]
        [Display(Name = "Опис гри")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Поле {0} є обов'язковим.")]
        [Display(Name = "Мінімальна кількість гравців")]
        [RegularExpression("0?[123456789][0]?", ErrorMessage = "Введіть обмеження по гравцям від 1 до 10")]
        public int MinAmountOfPlayers { get; set; }

        [Required(ErrorMessage = "Поле {0} є обов'язковим.")]
        [Display(Name = "Максимальна кількість гравців")]
        [RegularExpression("0?[123456789][0]?", ErrorMessage = "Введіть обмеження по гравцям від 1 до 10")]
        [GreaterThan(nameof(MinAmountOfPlayers))]
        public int MaxAmountOfPlayers { get; set; }

        [Required(ErrorMessage = "Поле {0} є обов'язковим.")]
        [Display(Name = "Мінімальне вікове обмеження")]
        [RegularExpression("0?[123456789][0123456789]?[0123456789]?", ErrorMessage = "Введіть обмеження по часу гри в хвилинах від 1 до 999")]
        public long MinGameTime { get; set; }

        [Required(ErrorMessage = "Поле {0} є обов'язковим.")]
        [Display(Name = "Максимальне вікове обмеження")]
        [RegularExpression("0?[123456789][0123456789]?[0123456789]?", ErrorMessage = "Введіть обмеження по часу гри в хвилинах від 1 до 999")]
        public long MaxGameTime { get; set; }

        [Display(Name = "Вікові обмеження")]
        [RegularExpression("0?[123456789][0123456789]?", ErrorMessage = "Введіть обмеження віку від 1 до 99")]
        public int? MinAgeOfPlayers { get; set; }

        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual ICollection<GameImage> Images { get; set; }
    }
}

Rolling Tavern/Controllers/BoardGamesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rolling_Tavern.Data;
using Rolling_Tavern.Models;

namespace Rolling_Tavern.Controllers
{
    public class BoardGamesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private IWebHostEnvironment _appEnvironment;

        public BoardGamesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }
        public class CurrentState
        {
            public CurrentState()
            {

            }
            public CurrentState(List<BoardGame> games)
            {
                Games = games;
            }
            public List<BoardGame> Games { get; set; }

            public bool Admin { get; set; }
        }

        private async Task<string> UploadPicture(IFormFile gamePicture, BoardGame game, string order)
        {
            const string defaultPicturePath = "/GamePictures/defaultBoardGame.jpg";
            if (gamePicture == null)
            {
                return defaultPicturePath;
            }
            string format = "Mddyyyyhhmmsstt";
            string imagename = String.Format("{0}", DateTime.Now.ToString(format));
            string pictureType = gamePicture.ContentType;
            string pictureExtension = pictureType.Substring(pictureType.IndexOf("/") + 1);
            string gamePicturePath = "/GamePictures/" + game.GameName[0] + order + imagename + "." + pictureExtension;

            using (var fileStream = new FileStream(_appEnvironment.WebRootPath + gamePicturePath, FileMode.Create))
            {
                await gamePicture.CopyToAsync(fileStream);
            }

            return gamePicturePath;
        }

        public async Task<List<BoardGame>> GetBoardGamesAsync()
        {
            List<BoardGame> tempData = await _context.BoardGames.Where(i => i.GameId != 1).ToListAsync();
            foreach (var game in tempData)
            {
                game.Images = await _context.GameImages.Where(i => i.GameId == game.GameId).ToListAsync();
            }
            return tempData;
        }

        // GET: BoardGames
        public async Task<IActionResult> Index()
        {
            ApplicationUser user = null;
            if(User!=null)
            {
                user = await _userManager.GetUserAsync(User);
            }
            var data = await GetBoardGamesAsync();
            CurrentState dataState = new CurrentState();
            dataState.Games = data;
            if(user!=null)
            {
                dataState.Admin = await _userManager.IsInRoleAsync(user, "admin");
            }
            else
            {
                dataState.Admin = false;
            }
            return View(dataState);
        }

        // GET: BoardGames/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boardGame = await _context.BoardGames
                .FirstOrDefaultAsync(m => m.GameId == id);
            List<GameImage> images = await _context.GameImages.Where(i => i.GameId == id).ToListAsync();
            boardGame.Images = images;

            if (boardGame == null)
            {
                return NotFound();
            }

            return View(boardGame);
        }

        // GET: BoardGames/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: BoardGames/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GameId,GameName,Genre,Description,MinAmountOfPlayers,MaxAmountOfPlayers,MinGameTime,MaxGameTime,MinAgeOfPlayers")] BoardGame boardGame, 
            IFormFile gamePicture1, IFormFile gamePicture2, IFormFile gamePicture3, IFormFile gamePicture4)
        {
            if (ModelState.IsValid)
            {
                if(boardGame.MinAgeOfPlayers==null)
                {
                    boardGame.MinAgeOfPlayers = 6;
                }
                BoardGame newBoardGame = new()
                {
                    GameName = boardGame.GameName,
                    Genre = boardGame.Genre,
                    Description = boardGame.Description,
                    MinAmountOfPlayers = boardGame.MinAmountOfPlayers,
                    MaxAmountOfPlayers = boardGame.MaxAmountOfPlayers,
                    MinGameTime = boardGame.MinGameTime,
                    MaxGameTime = boardGame.MaxGameTime,
                    MinAgeOfPlayers = boardGame.MinAgeOfPlayers
                };
                _context.Add(newBoardGame);
                await _context.SaveChangesAsync();
                BoardGame createdGame = await _context.BoardGames.OrderBy(i=>i.GameId).LastOrDefaultAsync();
                string path1 = null;
                string path2 = null;
                string path3 = null;
                string path4 = null;
                int counter = 0;
                if (gamePicture1 != null)
                {
                    path1 = await UploadPicture(gamePicture1, createdGame, "1");
                    counter++;
                }
                if (gamePicture2 != null)
                {
                    path2 = await UploadPicture(gamePicture2, createdGame, "2");
                    counter++;
                }
                if (gamePicture3 != null)
                {
                    path3 = await UploadPicture(gamePicture3, createdGame, "3");
                    counter++;
                }
                if (gamePicture4 != null)
                {
                    path4 = await UploadPicture(gamePicture4, createdGame, "4");
                    counter++;
                }
                if (counter==0)
                {
                    path1 = await UploadPicture(gamePicture1, createdGame, "1");
                }
                List<string> paths = new List<string>();
                paths.Add(path1);
                paths.Add(path2);
                paths.Add(path3);
                paths.Add(path4);
                foreach (var path in paths)
                {
                    if (path != null)
                    {
                        GameImage newImage = new()
                        {
                            ImagePath = path,
                            GameId = createdGame.GameId
                        };
                        _context.GameImages.Add(newImage);
                    }
                } 
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(boardGame);
        }

        // GET: BoardGames/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            BoardGame boardGame = await _context.BoardGames.FirstOrDefaultAsync(i => i.GameId == id);
            if (boardGame == null)
            {
                return NotFound();
            }
            List<GameImage> images = await _context.GameImages.Where(i=>i.GameId==id).ToListAsync();
            boardGame.Images = images;
            return View(boardGame);
        }

        // POST: BoardGames/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GameId,GameName,Genre,Description,MinAmountOfPlayers,MaxAmountOfPlayers,MinGameTime,MaxGameTime,MinAgeOfPlayers")] BoardGame boardGame,
            IFormFile gamePicture1, IFormFile gamePicture2, IFormFile gamePicture3, IFormFile gamePicture4)
        {
            if (id != boardGame.GameId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                BoardGame game = await _context.BoardGames.FirstOrDefaultAsync(i => i.GameId == boardGame.GameId);
                game.GameName = boardGame.GameName;
                game.Genre = boardGame.Genre;
                game.Description = boardGame.Description;
                game.MinAmountOfPlayers = boardGame.MinAmountOfPlayers;
                game.MaxAmountOfPlayers = boardGame.MaxAmountOfPlayers;
                game.MinGameTime = boardGame.MinGameTime;
                game.MaxGameTime = boardGame.MaxGameTime;
                game.MinAgeOfPlayers = boardGame.MinAgeOfPlayers;
                await _context.SaveChangesAsync();
                BoardGame editedGame = await _context.BoardGames.FirstOrDefaultAsync(i => i.GameId == boardGame.GameId);
                List<GameImage> images = await _context.GameImages.Where(i => i.GameId == boardGame.GameId).ToListAsync();
                string path1 = null;
                string path2 = null;
                string path3 = null;
                string path4 = null;
                int count = images.Count();
                if(count==1)
                {

Rolling Tavern/Views/BoardGames/Create.cshtml
@model Rolling_Tavern.Models.BoardGame

@{
    ViewData["Title"] = "Create";
}

<center>
    <h1>Створити нову гру</h1>
</center>
<hr />
<center>
    <h5>Час гри треба вводити в хвилинах.</h5>
</center>

<div class="page-content" onload="setAddress()">
    <form asp-action="Create" method="post" enctype="multipart/form-data">
        <div class="row justify-content-around">
            <div class="col-4" style="margin-left:250px; width:fit-content;">
                <div class="form-row profile-row">
                    <div class="col-md-8">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="GameName" class="control-label"></label>
                            <input asp-for="GameName" class="form-control" />
                            <span asp-validation-for="GameName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Genre" class="control-label"></label>
                            <input asp-for="Genre" class="form-control" />
                            <span asp-validation-for="Genre" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MinAgeOfPlayers" class="control-label"></label>
                            <input asp-for="MinAgeOfPlayers" min="6" class="form-control" />
                            <span asp-validation-for="MinAgeOfPlayers" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4" id="mod" style="right:100px">
                <div class="form-row profile-row">
                    <div class="col-md-8">

                        <div class="form-group">
                            <label asp-for="MinAmountOfPlayers" class="control-label"></label>
                            <input asp-for="MinAmountOfPlayers" min="1" id="minA" value="2" max="4" class="form-control"/>
                            <span asp-validation-for="MinAmountOfPlayers" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MaxAmountOfPlayers" class="control-label"></label>
                            <input asp-for="MaxAmountOfPlayers" id="maxA" value="5" min="3" class="form-control"/>
                            <span asp-validation-for="MaxAmountOfPlayers" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MinGameTime" class="control-label">Мінімальний час гри</label>
                            <input asp-for="MinGameTime" id="minT" min="1" max="29" value="10" class="form-control" />
                            <span asp-validation-for="MinGameTime" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MaxGameTime" class="control-label">Максимальний час гри</label>
                            <input asp-for="MaxGameTime" id="maxT" min="11" value="30" class="form-control" />
                            <span asp-validation-for="MaxGameTime" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <center>
            <div class="form-group">
                <label>Оберіть до чотирьох фотографій</label>
            </div>
            <div style="width:fit-content; display:inline-block">
                <div class="form-group">
                    <label>Фото гри: </label>
                    <input type="file" name="gamePicture1" id="fileUpload1" accept=".png,.jpg,.jpeg,.gif" onchange="readURL(this, 1)" />
                    <span id="photo1" class="text-danger"></span>
                    <div style="text-align:center">
                        <img id="game1" src="#" alt="Оберіть фото" style="margin-top:10px;" />
                    </div>
                </div>
                <div class="form-group">
                    <label>Фото гри: </label>
                    <input type="file" name="gamePicture2" id="fileUpload2" accept=".png,.jpg,.jpeg,.gif" onchange="readURL(this, 2)" />
                    <span id="photo2" class="text-danger"></span>
                    <div style="text-align:center">
                        <img id="game2" src="#" alt="Оберіть фото" style="margin-top:10px;" />
                    </div>
                </div>
            </div>
            <div style="display: inline-block; width:fit-content; ">
                <div class="form-group">
                    <label>Фото гри: </label>
                    <input type="file" name="gamePicture3" id="fileUpload3" accept=".png,.jpg,.jpeg,.gif" onchange="readURL(this, 3)" />
                    <span id="photo3" class="text-danger"></span>
                    <div style="text-align: center;">
                        <img id="game3" src="#" alt="Оберіть фото" style="margin-top:10px;" />
                    </div>
                </div>
                <div class="form-group">
                    <label>Фото гри: </label>
                    <input type="file" name="gamePicture4" id="fileUpload4" accept=".png,.jpg,.jpeg,.gif" onchange="readURL(this, 4)" />
                    <span id="photo4" class="text-danger"></span>
                    <div style="text-align: center;">
                        <img id="game4" src="#" alt="Оберіть фото" style="margin-top:10px;" />
                    </div>
                </div>

            </div>

            <div class="form-group">
                <input type="submit" value="Створити" class="nav-link text-white" style="text-align: center; font-family: Bluu Next Cyrillic; background: #B82406; border-radius: 5px;
                            padding: 5px; padding-left: 10px; padding-right: 10px; width:10%;" />
            </div>
            <div>
                <a asp-action="Index" class="text-muted">До списку ігор</a>
            </div>
        </center>
    </form>

</div>

<style>
    input, label, h1, h4, h5 {
        font-family: 'Bluu Next Cyrillic';
    }

    body {
        margin: 0;
        padding: 0;
    }
</style>
<script>
    var minInput = document.getElementById("minA");
    var maxInput = document.getElementById("maxA");
    minInput.onchange = function (e) {
        var min = document.getElementById("minA").value;
        document.getElementById("maxA").min = (parseInt(min) + 1);
        console.log("entered1");
    };
    maxInput.onchange = function (e) {
        var max = document.getElementById("maxA").value;
        document.getElementById("minA").max = (parseInt(max) - 1);
        console.log("entered2");
    }

    var minTInput = document.getElementById("minT");
    var maxTInput = document.getElementById("maxT");
    minTInput.onchange = function (e) {
        var min = document.getElementById("minT").value;
        document.getElementById("maxT").min = (parseInt(min) + 1);
        console.log("entered1");
    };
    maxTInput.onchange = function (e) {
        var max = document.getElementById("maxT").value;
        document.getElementById("minT").max = (parseInt(max) - 1);
        console.log("entered2");
    }

    function readURL(input, order) {
        if (input.files && input.files[0]) {
            var num = order;
            var reader = new FileReader();
            var spanId = '#photo' + num;
            var imgId = '#game' + num;
            var inputId = 'fileUpload' + num;
            reader.onload = function (e) {
                if (checkExt(inputId)) {
                    $(imgId)
                        .attr('src', e.target.result)
                        .width(300)
                        .height(300);
                    $(spanId).text('');
                }
                else {
                    $(spanId).text('Ви обрали недоступне розширення для файлу. Доступні: .png, .jpg, .jpeg, .gif.');
                    var file = document.getElementById(inputId);
                    file.value = '';
                    $(imgId).attr('src', '#');
                }
            };

            reader.readAsDataURL(input.files[0]);
        }
    }

    function checkExt(inputId) {
        var file = document.getElementById(inputId);
        var ext = file.value.match(/\.([^\.]+)$/)[1];
        switch (ext) {
            case 'jpg':
            case 'jpeg':
            case 'png':
            case 'gif':
                return true;
            default:
                this.value = '';
                return false;
        }
    }

</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rolling Tavern/Views/BoardGames/Index.cshtml
@model Rolling_Tavern.Controllers.BoardGamesController.CurrentState

@{
    ViewData["Title"] = "Index";
}

<div class="container page-content" onload="slide()">
    @if (Model.Admin)
    {
        <a class="nav-link text-white" asp-area="" asp-controller="BoardGames" asp-action="Create" style="width: 20%; text-align: center; background: #B82406; border-radius: 5px; margin-bottom: 20px;">Створити гру</a>
    }
    <div class="row justify-content-md-center" style="margin-left:auto; margin-right:auto;">
        @if (Model.Games?.Any() == true)
        {
            @foreach (var boardGame in Model.Games)
            {

                <div class="col-sm-4">
                    <div class="card" style="margin-bottom: 30px; margin-left: 20px; width: 275px; height: 440px; border-radius: 10px; box-shadow: 0.4em 0.4em 5px rgba(122,122,122,0.5);">
                        <div style="margin-left:auto; margin-right:auto;">
                            @if (boardGame.Images.Count() != 0)
                            {
                                <div id="carousel+@boardGame.GameId" class="carousel slide" data-bs-ride="carousel">
                                    <div class="carousel-inner">
                                        @{
                                            bool checkFirst = true;
                                        }
                                        @foreach (var photo in boardGame.Images)
                                        {
                                            if (checkFirst)
                                            {
                                                <div class="carousel-item active">
                                                    <img src="@photo.ImagePath" class="d-block w-100" style="max-height: 160px; max-width: 275px">
                                                </div>
                                                checkFirst = false;
                                            }
                                            else
                                            {
                                                <div class="carousel-item">
                                                    <img src="@photo.ImagePath" class="d-block w-100" style="max-height: 160px; max-width: 275px">
                                                </div>
                                            }
                                        }
                                    </div>
                                </div>
                            }
                            else
                            {
                                <img class="card-img-top" src="~/BoardGamesPicture/defaultBoardGame.jpg" style="max-height: 160px; max-width: 275px">
                            }
                        </div>
                        @{
                            double minTime = (double)boardGame.MinGameTime;
                            double maxTime = (double)boardGame.MaxGameTime;
                            string minTimeRes = "";
                            string maxTimeRes = "";
                            if (minTime >= 60)
                            {
                                minTimeRes += Math.Floor(minTime / 60).ToString();
                                minTimeRes += "H ";
                                if (minTime % 60 != 0)
                                {
                                    minTimeRes += (minTime % 60).ToString();
                                    minTimeRes += "M ";
                                }
                            }
                            else
                            {
                                minTimeRes += (minTime % 60).ToString();
                                minTimeRes += "M ";
                            }
                            if (maxTime >= 60)
                            {
                                maxTimeRes += Math.Floor(maxTime / 60).ToString();
                                maxTimeRes += "H ";
                                if (maxTime % 60 != 0)
                                {
                                    maxTimeRes += (maxTime % 60).ToString();
                                    maxTimeRes += "M ";
                                }
                            }
                            else
                            {
                                maxTimeRes += (maxTime % 60).ToString();
                                maxTimeRes += "M";
                            }
                        }
                        <a href="/BoardGames/Details/@boardGame.GameId">
                            <div class="card-body" style="text-align:center">
                                <h5 class="card-title">@boardGame.GameName</h5>
                                <h6 class="card-text"><img src="~/images/time.png" style="height: 30px; margin-bottom: 1%; display: inline-block; width: 30px" /> @minTimeRes- @maxTimeRes</h6>
                                <h6 class="card-text"><img src="~/images/group.png" style="height: 30px; margin-bottom: 1%; display: inline-block; width: 30px" /> @boardGame.MinAmountOfPlayers - @boardGame.MaxAmountOfPlayers</h6>
                                <h6 class="card-text"><img src="~/images/age.png" style="height: 30px; margin-bottom: 1%; display: inline-block; width: 30px" /> +@boardGame.MinAgeOfPlayers</h6>
                                <h6 class="card-text"> Жанр гри: @boardGame.Genre</h6>
                            </div>
                        </a>
                    </div>

                </div>

            }
        }
        else
        {
            <h2>Інших ігор немає.</h2>
        }
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
    function slide() {
        $('.carousel').carousel({
            interval: 5500
        });
        $('.carousel').carousel('cycle', {
            interval: 5500
        });
    }
    $('.carousel').carousel({
        interval: 5500
    });
</script>