Rolling Tavern/Models/Meeting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore.Storage;

#nullable disable

namespace Rolling_Tavern.Models
{
    public partial class Meeting
    { 
        public int MeetingId { get; set; }

        [Required(ErrorMessage = "Поле {0} є обов'язковим.")]
        [StringLength(32, ErrorMessage = "{0} повиннa бути не менше {2} та не більше {1} літер", MinimumLength = 4)]
        [Display(Name = "Назва зустрічі")]
        public string MeetingName { get; set; }

        //[Required(ErrorMessage = "{0} повинні бути обрані.")]
        [Display(Name = "Дата та час проведення зустрічі")]
        [DataType(DataType.DateTime)]
        public DateTime DateOfMeeting { get; set; }

        [Required(ErrorMessage = "Поле {0} є обов'язковим.")]
        [Display(Name = "Адреса зустрічі")]
        public string AddresOfMeeting { get; set; }

        [DataType(DataType.Text)]
        [StringLength(1000, ErrorMessage = "{0} повинно бути не більше {1} літер", MinimumLength = 1)]
        [Display(Name = "Опис зустрічі")]
        public string Description { get; set; }

        [DataType(DataType.Text)]
        [StringLength(1000, ErrorMessage = "{0} повинно бути не більше {1} літер", MinimumLength = 1)]
        [Display(Name = "Додаткові вимоги")]
        public string AdditionalRequirements { get; set; }

        [Display(Name = "Фото зустрічі")]
        [AllowedExtensions(new string[] { ".png", ".jpg", ".jpeg", ".gif" })]
        public string PhotoLink { get; set; }
        public long? CreatorId { get; set; }
        public int? GameId { get; set; }
        

        [Display(Name = "Вікові обмеження")]
        [RegularExpression("0?[123456789][0123456789]?", ErrorMessage = "Введіть обмеження віку від 1 до 99")]
        public int? MinimalAge { get; set; }

        public virtual BoardGame Game { get; set; }
        public virtual ApplicationUser Creator { get; set; }

        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}

Rolling Tavern/Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rolling_Tavern.Data;
using Rolling_Tavern.Enums;
using Rolling_Tavern.Models;

namespace Rolling_Tavern.Controllers
{
    public class MeetingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private IWebHostEnvironment _appEnvironment;

        public MeetingController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }
        public class CurrentInfo
        {
            public ApplicationUser CurrentUser;
            public Meeting CurrentMeeting;
            public bool Role { get; set; }
            public bool CommentsEmpty { get; set; }
            public bool UserCommentEmpty { get; set; }
            public CurrentInfo() {}
            public CurrentInfo(ApplicationUser user ,Meeting meeting)
            {
                CurrentUser = user;
                CurrentMeeting = meeting;
            }
        }
        public class UserInfo
        {
            public ApplicationUser User;
            public List<Meeting> Meetings;
            public UserInfo() {}
            public UserInfo(ApplicationUser user, List<Meeting> meetings)
            {
                User = user;
                Meetings = meetings;
            }
        }
        private async Task<string> UploadPicture(IFormFile profilePicture, Meeting meeting)
        {
            //var game = await _context.BoardGames.Where(i => i.GameId == meeting.GameId).FirstOrDefaultAsync();
            string defaultPicturePath;
            if (meeting.GameId==1)
            {
                defaultPicturePath = "/GamePictures/defaultBoardGame.jpg";
            }
            else
            {
                var picrutures = await _context.GameImages.Where(i => i.GameId == meeting.GameId).ToListAsync();
                defaultPicturePath = picrutures.First().ImagePath;
            }
            if (profilePicture == null)
            {
                return defaultPicturePath;
            }
            var user = await _userManager.GetUserAsync(User);
            string userId = await _userManager.GetUserIdAsync(user);
            string format = "Mddyyyyhhmmsstt";
            string imagename = String.Format("{0}", DateTime.Now.ToString(format));
            string pictureType = profilePicture.ContentType;
            string pictureExtension = pictureType.Substring(pictureType.IndexOf("/") + 1);
            string profilePicturePath = "/MeetingPictures/" + userId + meeting.MeetingName[0] + imagename + "." + pictureExtension;

            using (var fileStream = new FileStream(_appEnvironment.WebRootPath + profilePicturePath, FileMode.Create))
            {
                await profilePicture.CopyToAsync(fileStream);
            }

            return profilePicturePath;
        }


        private async Task<IEnumerable<Meeting>> GetMeetings()
        {
            List<Meeting> Meetings = new List<Meeting>();
            var allMeetings = await _context.Meetings.Where(d => d.DateOfMeeting > DateTime.Now && d.Creator != null).ToListAsync();
            if(allMeetings?.Any()==true)
            {
                foreach(var item in allMeetings)
                {
                    List<Request> requests = await _context.Requests.Where(i => i.MeetingId == item.MeetingId).ToListAsync();
                    ApplicationUser creator = await _context.Users.FirstOrDefaultAsync(u => u.Id == item.CreatorId);
                    BoardGame game = await _context.BoardGames.Where(g => g.GameId == item.GameId).FirstOrDefaultAsync();
                    Meetings.Add(new Meeting
                    {
                        MeetingId = item.MeetingId,
                        MeetingName = item.MeetingName,
                        DateOfMeeting = item.DateOfMeeting,
                        AddresOfMeeting = item.AddresOfMeeting,
                        Description = item.Description,
                        AdditionalRequirements = item.AdditionalRequirements,
                        PhotoLink = item.PhotoLink,
                        CreatorId = item.CreatorId,
                        MinimalAge = item.MinimalAge,
                        GameId = item.GameId,
                        Game = game,
                        Creator = creator,
                        Requests = requests
                    });
                }    
            }
            return Meetings;
        }

        // GET: Meeting
        //public async Task<ViewResult> Index()
        //{
        //    var data = await GetMeetings();
        //    return View(data);
        //}


        public async Task<ViewResult> Index(string sortOrder, string searchString)
        {
            var meetings = await GetMeetings();
          
                ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //var games = await _context.BoardGames.ToListAsync();
            var users = await _context.Users.ToListAsync();
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;


            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                meetings = meetings.Where(s => s.MeetingName.ToLower().Contains(searchString)
                                               || s.AddresOfMeeting.ToLower().Contains(searchString)
                                               || s.Game.GameName.ToLower().Contains(searchString)
                                               || s.Game.Genre.ToLower().Contains(searchString)
                                               || s.Creator.UserName.ToLower().Contains(searchString)
                                               || s.Creator.FirstName.ToLower().Contains(searchString)
                                               || s.Creator.LastName.ToLower().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    meetings = meetings.OrderByDescending(s => s.MeetingName);
                    break;
                case "Date":
                    meetings = meetings.OrderBy(s => s.DateOfMeeting);
                    break;
                case "date_desc":
                    meetings = meetings.OrderByDescending(s => s.DateOfMeeting);
                    break;
                default:
                    meetings = meetings.OrderBy(s => s.MeetingName);
                    break;
            }
            return View(meetings);
        }

        // GET: Meeting/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return null;
            }
            else
            {
                ApplicationUser currentUser = await _userManager.GetUserAsync(User);
                var temp = await _context.Meetings.Where(m => m.MeetingId == id).FirstOrDefaultAsync();
                BoardGame game = await _context.BoardGames.Where(i => i.GameId == temp.GameId).FirstOrDefaultAsync();
                ApplicationUser creator = await _context.Users.Where(i => i.Id == temp.CreatorId).FirstOrDefaultAsync();
                List<Request> requests = await _context.Requests.Where(i => i.MeetingId == temp.MeetingId).ToListAsync();
                List<Comment> comments = null;
                bool empty = true;
                bool userComment = true;
                if(_context.Comments.Where(i => i.MeetingId==id).Any())
                {
                    comments = await _context.Comments.Where(i => i.MeetingId == id).ToListAsync();
                    foreach (var comm in comments)
                    {
                        comm.Author = await _context.Users.Where(i => i.Id == comm.AuthorId).FirstOrDefaultAsync();
                    }
                    empty = false;
                    userComment = !comments.Where(i => i.AuthorId == currentUser.Id).Any();
                }
                foreach(var item in requests)
                {
                    item.User = await _context.Users.Where(i => i.Id == item.UserId).FirstAsync();
                }
                Meeting meeting = new Meeting
                {
                    MeetingId = temp.MeetingId,
                    MeetingName = temp.MeetingName,
                    DateOfMeeting = temp.DateOfMeeting,
                    AddresOfMeeting = temp.AddresOfMeeting,
                    Description = temp.Description,
                    AdditionalRequirements = temp.AdditionalRequirements,
                    PhotoLink = temp.PhotoLink,
                    CreatorId = temp.CreatorId,
                    MinimalAge = temp.MinimalAge,
                    GameId = temp.GameId,
                    Game = game,
                    Creator = creator,
                    Requests = requests,
                    Comments = comments
                };
                if (meeting == null)
                {
                    return null;
                }
                CurrentInfo info = new()
                {
                    CurrentUser = currentUser,
                    CurrentMeeting = meeting
                };
                info.CommentsEmpty = empty;
                info.UserCommentEmpty = userComment;

Rolling Tavern/Controllers/UserProfileController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Rolling_Tavern.Data;
using Rolling_Tavern.Models;
using Rolling_Tavern.Services;
using Rolling_Tavern.ViewModel;

namespace Rolling_Tavern.Controllers
{
    [Authorize]
    public class UserProfileController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly MeetingsManager _meetingsManager;

        public UserProfileController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _meetingsManager = new MeetingsManager();
        }

      

        [HttpGet]
        public async Task<IActionResult> Index(long id, int meetingId)
        {
            var user = await _userManager.FindByIdAsync(id.ToString());
            if (user != null)
            {
                var storyOfMeetings = await _meetingsManager.GetStoryOfMeetings(user, _context);
                var meetings = new List<Meeting>();
                var tempmeetings = storyOfMeetings.OrderByDescending(d => d.DateOfMeeting);
                int count = 5;
                foreach (var item in tempmeetings)
                {
                    if (count <= 0)
                        break;
                    else
                    {
                        meetings.Add(item);
                        count--;
                    }
                }
                UserProfileViewModel viewModel = new UserProfileViewModel()
                {
                    User = user,
                    StoryOfMeetings = meetings
                };
                viewModel.MeetingID = meetingId;
                return View(viewModel);
            }

            return NotFound();
        }
    }
}

Rolling Tavern/Views/Meeting/Create.cshtml
@model Rolling_Tavern.Models.Meeting

@{
    ViewData["Title"] = "Create";
}

<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
<link href="https://api.mapbox.com/mapbox-gl-js/v2.6.0/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.6.0/mapbox-gl.js"></script>
<style>
    body {
        margin: 0;
        padding: 0;
    }

    #map {
        height: 71%;
        top: 0;
        bottom: 0;
        width: 100%;
    }
</style>
<script src="~/js/map.js"></script>
<script>
    // TO MAKE THE MAP APPEAR YOU MUST
    // ADD YOUR ACCESS TOKEN FROM
    // https://account.mapbox.com
    mapboxgl.accessToken = 'pk.eyJ1IjoidHN1cmlrYXBwYSIsImEiOiJja3Z3anY2czcwZjU1Mm5vZWZjNDF3YXppIn0.15HnrAoUseWpJvYgD8a1eg';
    const mapboxClient = mapboxSdk({ accessToken: mapboxgl.accessToken });
    var address;
    let form = document.querySelector("#address");
    form.addEventListener("input", () => {
        setAddress();
    });
    function setAddress() {
        document.getElementById('mod').style = "min-height: 590px; right: 100px";
        let form = document.querySelector("#address");
        var input = form.value;
        address = input;
        mapboxClient.geocoding
            .forwardGeocode({
                query: address + ', Харьков',
                autocomplete: false,
                limit: 1
            })
            .send()
            .then((response) => {
                if (
                    !response ||
                    !response.body ||
                    !response.body.features ||
                    !response.body.features.length
                ) {
                    console.error('Invalid response:');
                    console.error(response);
                    return;
                }
                const feature = response.body.features[0];

                const map = new mapboxgl.Map({
                    container: 'map',
                    style: 'mapbox://styles/mapbox/streets-v11',
                    center: feature.center,
                    zoom: 10
                });

                // Create a marker and add it to the map.
                new mapboxgl.Marker().setLngLat(feature.center).addTo(map);
            });
    }
</script>
<div class="page-content">
    <h2 style="text-align:center">Створення гуртка</h2>
    <hr style="width:60vw" />
    <h6 style="text-align:center">* - Обов'язкові поля</h6>
    <form asp-action="Create" method="post" enctype="multipart/form-data">

        <div class="row justify-content-around">
            <div class="col-4" style="margin-left:250px">
                <div class="form-row profile-row">
                    <div class="col-md-8">
                        <div class="form-group">
                            <label asp-for="MeetingName">*Назва гуртка: </label>
                            <input asp-for="MeetingName" class="form-control" enabled />
                            <span asp-validation-for="MeetingName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="PhotoLink">Фото гуртка: </label>
                            <input type="file" name="meetingPicture" id="fileUpload" accept=".png,.jpg,.jpeg,.gif" onchange="readURL(this)" />
                            <span asp-validation-for="PhotoLink" id="photo" class="text-danger"></span>
                            <div style="text-align:center">
                                <img id="meet" src="#" alt="Оберіть фото" style="margin-top:10px;" />
                            </div>
                        </div>
                        <div class="form-group">
                            <input value="@DateTime.Now.Date.AddYears(+100).ToString("yyyy-MM-dd")" type="hidden" asp-for="DateOfMeeting" class="form-control"  min="@DateTime.Now.ToString("yyyy-MM-ddTHH:mm")"/>
                            <span asp-validation-for="DateOfMeeting" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AddresOfMeeting">*Адреса гуртка: </label>
                            <input asp-for="AddresOfMeeting" class="form-control" id="address" enabled />
                            <span asp-validation-for="AddresOfMeeting" class="text-danger"></span>
                        </div>
                       
                        <div class="form-group">
                            <label asp-for="Description">Опис гуртка: </label>
                            <textarea asp-for="Description" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4" id="mod" style="right:100px">
                <div class="form-row profile-row">
                    <div class="col-md-8">
                        @*<div style="visibility: hidden" class="form-group">
                            <label>Назва гри: </label>
                            <select value="1" asp-for="GameId" class="form-control" asp-items="ViewBag.GameId"></select>
                        </div>*@
                        <div class="form-group">
                            <label>Вікові обмеження: </label>
                            <input asp-for="MinimalAge" class="form-control" enabled />
                            <span asp-validation-for="MinimalAge" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="AdditionalRequirements">Додаткові вимоги: </label>
                            <textarea asp-for="AdditionalRequirements" class="form-control" id="exampleFormControlTextarea1" rows="3" style="resize: none;"></textarea>
                            <span asp-validation-for="AdditionalRequirements" class="text-danger"></span>
                        </div>
                        <div>
                            <input type="button" value="Перевірити адресу" style="border-radius:3px;font-family: 'Bluu Next Cyrillic' ;margin-top:8px;margin-bottom:8px; background: #B82406;font-size:16px;color:white;" onclick="setAddress()">
                        </div>
                        <div id="map"></div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <center>
                <div class="form-group">
                    <input type="submit" style="font-family: 'Bluu Next Cyrillic'; background: #B82406;font-size:20px;margin-top:30px" value="Створити" class="btn btn-primary" />
                </div>
                <div>
                    <a asp-action="Index" style="text-align:right;color:#333333;" class="text-muted">До списку гуртків</a>
                </div>
            </center>
        </div>
    </form>
</div>
<style>
    .form-group, h2, h6{
        font-family:'Bluu Next Cyrillic';
        color:#333333;
    }
</style>

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                if (checkExt()) {
                    $('#meet')
                        .attr('src', e.target.result)
                        .width(300)
                        .height(300);
                    $('#photo').text('');
                }
                else {
                    $('#photo').text('Ви обрали недоступне розширення для файлу. Доступні: .png, .jpg, .jpeg, .gif.');
                    var file = document.getElementById('fileUpload');
                    file.value = '';
                    $('#meet').attr('src', '#');
                }
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
    function checkExt() {
        var file = document.getElementById('fileUpload');
        var ext = file.value.match(/\.([^\.]+)$/)[1];
            switch (ext) {
                case 'jpg':
                case 'jpeg':
                case 'png':
                case 'gif':
                    return true;
                default:
                    this.value = '';
                    return false;
            }
    }
    
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rolling Tavern/Views/Meeting/Index.cshtml
@using System.Security.Cryptography
@model IEnumerable<Rolling_Tavern.Models.Meeting>
@{ 
    ViewData["Title"] = "Meeting";
} 
<div class="container page-content">
    
    
    <form class="my-2" asp-action="Index" method="get">
        <div class="form-row">
            
            <input class="form-control mr-sm-2 col-6" style="margin-left: auto" placeholder="Пошук" type="text" name="SearchString" value="@ViewData["CurrentFilter"]"/>
            
            <div class="form-group">

                <select id="sortOrder" class="form-control" name="sortOrder">

                    <option value="@ViewData["NameSortParm"]">Cортувати за назвою</option>
                    <option value="@ViewData["DateSortParm"]">Сортувати за датою</option>
                </select>
            </div>
           

            <div class="col-3" >
                <input type="submit" value="Знайти" class="btn btn-dark"/> |
                <a asp-action="Index">Всі гуртки</a>
            </div>
            
        </div>
    </form>

    <div class="row justify-content-md-center" style="margin-left: auto; margin-right: auto;">
        @if (Model?.Any() == true)
        {
            @foreach (var meeting in Model)
            {
                <a href="/Meeting/Details/@meeting.MeetingId">
                    <div class="col-sm-4">
                        <div class="card" style="margin-bottom: 30px; margin-left: 20px; width: 275px; height: 380px; border-radius: 10px; box-shadow: 0.4em 0.4em 5px rgba(122, 122, 122, 0.5);">
                            <div style="margin-left: auto; margin-right: auto; margin-top: 5px;">
                                @if (meeting.PhotoLink != null)
                                {
                                    <img class="card-img-top" src="@meeting.PhotoLink" style="max-height: 160px; max-width: 275px">
                                }
                                else
                                {
                                    <img class="card-img-top" src="~/BoardGamesPicture/defaultBoardGame.jpg" style="max-height: 160px; max-width: 275px">
                                }
                            </div>
                            <div class="card-body" style="text-align: center">
                                <h5 class="card-title">@meeting.MeetingName</h5>
                                @if (meeting.CreatorId != null)
                                {
                                    <h6 class="card-text">@meeting.Creator.FirstName<img src="~/images/crown.png" style="height: 30px; margin-bottom: 1%; display: inline-block; width: 30px"/></h6>
                                }
                                else
                                {
                                    <h6 class="card-text">Deleted User<img src="~/images/crown.png" style="height: 30px; margin-bottom: 1%; display: inline-block; width: 30px"/></h6>
                                }
                                @if (meeting.MinimalAge != null)
                                {
                                    <h6 class="card-text">
                                        <img src="~/images/DefaultUser.png" style="margin-bottom: 1%; height: 30px; display: inline-block; margin-left: 1%; width: 30px"/>
                                        +@meeting.MinimalAge.Value
                                    </h6>
                                }
                                <h6 class="card-text">@meeting.AddresOfMeeting</h6>
                                

                            </div>

                        </div>

                    </div>
                </a>
            }
        }
        else
        {
            <h3>Нажаль за вашим запитом зустрічей не знайдено.</h3>
        }
    </div>
</div>

Rolling Tavern/Views/Meeting/ShowRequests.cshtml
@using Rolling_Tavern.Services
@model Rolling_Tavern.Models.Meeting
@{
    ViewData["Title"] = "Requests";
    
}
<div class="container page-content">
    <h2 style="text-align:center">@Model.MeetingName</h2>
    <section style="background-color: white; color: black; border: 1px solid black; height: fit-content; width: 100%; border-radius: 10px; margin-left:5%">
        @if (Model.Requests.Any() == true)
        {
            <table cellpadding="10" style="margin-left:auto; margin-right: auto; table-layout:fixed;">
                <tr>
                    <th>
                        Фото профілю
                    </th>
                    <th>
                        Поштова скринька
                    </th>
                    <th>
                        Логін
                    </th>
                    <th>
                        Телефон
                    </th>
                    <th>
                        Рейтинг
                    </th>
                    <th>
                        Профіль
                    </th>
                    <th>
                        Стан
                    </th>
                    <th>
                        Дія
                    </th>
                </tr>
                @foreach (var item in Model.Requests)
                {
                    <tr>
                        <td>
                            <img src="@item.User.ProfilePicture" style="height: 40px; width: 40px;" />
                        </td>
                        <td>
                            <h6>@item.User.Email</h6>
                        </td>
                        <td>
                            <h6>@item.User.UserName</h6>
                        </td>
                        <td>
                            <h6>@item.User.PhoneNumber</h6>
                        </td>
                        <td>
                            <h6>
                                <center>
                                    <img src="@RatingManager.GetRatingImage(item.User.Rating)" alt="" style="height: 35px; width: 35px;">
                                </center>
                            </h6>
                        </td>
                        <td>
                            <form asp-controller="UserProfile" asp-action="Index" asp-route-id="@item.User.Id" method="get">
                                <input type="hidden" name="meetingId" value="@item.MeetingId" />
                                <input type="submit" value="Профіль" style="background: none; font-family: Bluu Next Cyrillic; font-size: 15px; border-radius: 5px; color: black;" />
                            </form>
                        </td>
                        <td>
                            <img src="@item.State.StateImage" style="height: 40px; width: 40px;" />
                        </td>
                        <td>
                            <form asp-action="ShowRequests" method="post">
                                <input type="hidden" name="userId" value="@item.User.Id" />
                                @if (item.StateId == 2)
                                {
                                    <input type="submit" name="response" value="Видалити" style="background: none; font-family: Bluu Next Cyrillic; font-size: 15px; border-radius: 5px; color: black;" />
                                }
                                @if (item.StateId == 1)
                                {
                                    <input type="submit" name="response" value="Додати" style="background: none; font-family: Bluu Next Cyrillic; font-size: 15px; border-radius: 5px; color: black;" />
                                    <input type="submit" name="response" value="Відмовити" style="background: #B82406; font-family: Bluu Next Cyrillic; font-size: 15px; border-radius: 5px; color: black;" />
                                }
                            </form>
                        </td>
                    </tr>

                }
            </table>
        }
        else
        {
            <h2 style="text-align:center;">Ще немає бажаючих приєднатися до зустрічі.</h2>
        }
        <center>
            <div class="form-group">
                <a href="/Meeting/Details/@Model.MeetingId" style="font-family: 'Bluu Next Cyrillic'; background: #B82406;font-size:20px;margin-top:30px;position:center" class="btn btn-primary">
                    Повернутися
                </a>
            </div>
        </center>
        
    </section>
   
</div>
<style>
    .form-group, h2, h3, h5, h6 {
        font-family: 'Bluu Next Cyrillic';
        color: #333333;
    }
</style>