Rolling Tavern/Controllers/AdminUserManageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Rolling_Tavern.Data;
using Rolling_Tavern.Models;

namespace Rolling_Tavern.Controllers
{
    [Authorize(Roles="admin")]
    public class AdminUserManageController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private IWebHostEnvironment _appEnvironment;

        public AdminUserManageController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }

        [HttpGet]
        public async Task<ViewResult> Index()
        {
            var UserIds = _context.UserRoles.Where(r => r.RoleId == 1).Select(r=>r.UserId).ToArray();
            IEnumerable<ApplicationUser> users =  _context.Users.Where(u=>UserIds.Contains(u.Id)).ToList();
            
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> BanUser(long id)
        {
            var user = await _userManager.FindByIdAsync(id.ToString());
            if (user != null)
            {
                var result= await _userManager.SetLockoutEndDateAsync(user,DateTime.Now.AddYears(100));
                return RedirectToAction("Index");

            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> UnbanUser(long id)
        {
            var user = await _userManager.FindByIdAsync(id.ToString());
            if (user != null)
            {
                var result = await _userManager.SetLockoutEndDateAsync(user, null);
                return RedirectToAction("Index");

            }

            return NotFound();
        }
    }
}

Rolling Tavern/Controllers/MeetingController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rolling_Tavern.Data;
using Rolling_Tavern.Enums;
using Rolling_Tavern.Models;

namespace Rolling_Tavern.Controllers
{
    public class MeetingController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private IWebHostEnvironment _appEnvironment;

        public MeetingController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }
        public class CurrentInfo
        {
            public ApplicationUser CurrentUser;
            public Meeting CurrentMeeting;
            public bool Role { get; set; }
            public bool CommentsEmpty { get; set; }
            public bool UserCommentEmpty { get; set; }
            public CurrentInfo() {}
            public CurrentInfo(ApplicationUser user ,Meeting meeting)
            {
                CurrentUser = user;
                CurrentMeeting = meeting;
            }
        }
        public class UserInfo
        {
            public ApplicationUser User;
            public List<Meeting> Meetings;
            public UserInfo() {}
            public UserInfo(ApplicationUser user, List<Meeting> meetings)
            {
                User = user;
                Meetings = meetings;
            }
        }
        private async Task<string> UploadPicture(IFormFile profilePicture, Meeting meeting)
        {
            //var game = await _context.BoardGames.Where(i => i.GameId == meeting.GameId).FirstOrDefaultAsync();
            string defaultPicturePath;
            if (meeting.GameId==1)
            {
                defaultPicturePath = "/GamePictures/defaultBoardGame.jpg";
            }
            else
            {
                var picrutures = await _context.GameImages.Where(i => i.GameId == meeting.GameId).ToListAsync();
                defaultPicturePath = picrutures.First().ImagePath;
            }
            if (profilePicture == null)
            {
                return defaultPicturePath;
            }
            var user = await _userManager.GetUserAsync(User);
            string userId = await _userManager.GetUserIdAsync(user);
            string format = "Mddyyyyhhmmsstt";
            string imagename = String.Format("{0}", DateTime.Now.ToString(format));
            string pictureType = profilePicture.ContentType;
            string pictureExtension = pictureType.Substring(pictureType.IndexOf("/") + 1);
            string profilePicturePath = "/MeetingPictures/" + userId + meeting.MeetingName[0] + imagename + "." + pictureExtension;

            using (var fileStream = new FileStream(_appEnvironment.WebRootPath + profilePicturePath, FileMode.Create))
            {
                await profilePicture.CopyToAsync(fileStream);
            }

            return profilePicturePath;
        }


        private async Task<IEnumerable<Meeting>> GetMeetings()
        {
            List<Meeting> Meetings = new List<Meeting>();
            var allMeetings = await _context.Meetings.Where(d => d.DateOfMeeting > DateTime.Now && d.Creator != null).ToListAsync();
            if(allMeetings?.Any()==true)
            {
                foreach(var item in allMeetings)
                {
                    List<Request> requests = await _context.Requests.Where(i => i.MeetingId == item.MeetingId).ToListAsync();
                    ApplicationUser creator = await _context.Users.FirstOrDefaultAsync(u => u.Id == item.CreatorId);
                    BoardGame game = await _context.BoardGames.Where(g => g.GameId == item.GameId).FirstOrDefaultAsync();
                    Meetings.Add(new Meeting
                    {
                        MeetingId = item.MeetingId,
                        MeetingName = item.MeetingName,
                        DateOfMeeting = item.DateOfMeeting,
                        AddresOfMeeting = item.AddresOfMeeting,
                        Description = item.Description,
                        AdditionalRequirements = item.AdditionalRequirements,
                        PhotoLink = item.PhotoLink,
                        CreatorId = item.CreatorId,
                        MinimalAge = item.MinimalAge,
                        GameId = item.GameId,
                        Game = game,
                        Creator = creator,
                        Requests = requests
                    });
                }    
            }
            return Meetings;
        }

        // GET: Meeting
        //public async Task<ViewResult> Index()
        //{
        //    var data = await GetMeetings();
        //    return View(data);
        //}


        public async Task<ViewResult> Index(string sortOrder, string searchString)
        {
            var meetings = await GetMeetings();
          
                ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //var games = await _context.BoardGames.ToListAsync();
            var users = await _context.Users.ToListAsync();
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;


            if (!String.IsNullOrEmpty(searchString))
            {
                searchString = searchString.ToLower();
                meetings = meetings.Where(s => s.MeetingName.ToLower().Contains(searchString)
                                               || s.AddresOfMeeting.ToLower().Contains(searchString)
                                               || s.Game.GameName.ToLower().Contains(searchString)
                                               || s.Game.Genre.ToLower().Contains(searchString)
                                               || s.Creator.UserName.ToLower().Contains(searchString)
                                               || s.Creator.FirstName.ToLower().Contains(searchString)
                                               || s.Creator.LastName.ToLower().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    meetings = meetings.OrderByDescending(s => s.MeetingName);
                    break;
                case "Date":
                    meetings = meetings.OrderBy(s => s.DateOfMeeting);
                    break;
                case "date_desc":
                    meetings = meetings.OrderByDescending(s => s.DateOfMeeting);
                    break;
                default:
                    meetings = meetings.OrderBy(s => s.MeetingName);
                    break;
            }
            return View(meetings);
        }

        // GET: Meeting/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return null;
            }
            else
            {
                ApplicationUser currentUser = await _userManager.GetUserAsync(User);
                var temp = await _context.Meetings.Where(m => m.MeetingId == id).FirstOrDefaultAsync();
                BoardGame game = await _context.BoardGames.Where(i => i.GameId == temp.GameId).FirstOrDefaultAsync();
                ApplicationUser creator = await _context.Users.Where(i => i.Id == temp.CreatorId).FirstOrDefaultAsync();
                List<Request> requests = await _context.Requests.Where(i => i.MeetingId == temp.MeetingId).ToListAsync();
                List<Comment> comments = null;
                bool empty = true;
                bool userComment = true;
                if(_context.Comments.Where(i => i.MeetingId==id).Any())
                {
                    comments = await _context.Comments.Where(i => i.MeetingId == id).ToListAsync();
                    foreach (var comm in comments)
                    {
                        comm.Author = await _context.Users.Where(i => i.Id == comm.AuthorId).FirstOrDefaultAsync();
                    }
                    empty = false;
                    userComment = !comments.Where(i => i.AuthorId == currentUser.Id).Any();
                }
                foreach(var item in requests)
                {
                    item.User = await _context.Users.Where(i => i.Id == item.UserId).FirstAsync();
                }
                Meeting meeting = new Meeting
                {
                    MeetingId = temp.MeetingId,
                    MeetingName = temp.MeetingName,
                    DateOfMeeting = temp.DateOfMeeting,
                    AddresOfMeeting = temp.AddresOfMeeting,
                    Description = temp.Description,
                    AdditionalRequirements = temp.AdditionalRequirements,
                    PhotoLink = temp.PhotoLink,
                    CreatorId = temp.CreatorId,
                    MinimalAge = temp.MinimalAge,
                    GameId = temp.GameId,
                    Game = game,
                    Creator = creator,
                    Requests = requests,
                    Comments = comments
                };
                if (meeting == null)
                {
                    return null;
                }
                CurrentInfo info = new()
                {
                    CurrentUser = currentUser,
                    CurrentMeeting = meeting
                };
                info.CommentsEmpty = empty;
                info.UserCommentEmpty = userComment;

Rolling Tavern/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        @ViewData["Title"]
    </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="~/css/Контакты.css" media="screen">
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.2/css/star-rating.min.css" />
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-star-rating/4.0.2/js/star-rating.min.js"></script>

</head>
<body>
    <partial name="_header" />
    @RenderBody()
    <partial name="_footer" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="/examples/vendors/jquery/jquery-3.3.1.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Rolling Tavern/Views/Shared/_footer.cshtml
<footer style="width: 100%; height: 60px; background: rgba(28, 0, 19, 1); position: absolute; bottom: 0">
    <div class="container">
        <center>
            <p class="dline">
                Rolling Tavern is the place where you can find hobby group according to your taste.<br />
                Copyright &copy; 2022 Rolling Tavern | All Rights Reserved
            </p>
        </center>
    </div>
</footer>

Rolling Tavern/Views/Shared/_header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3">
        <a class="navbar-brand" href="/" style="">
            <img src="~/images/LogoTavern.ico" width="120" height="65" i asp-append-version="true" />
        </a>

        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <ul class="navbar-nav">
                <partial name="_LoginPartial" />
            </ul>
            <ul class="navbar-nav flex-grow-1">

                @*<li class="nav-item dropdown">
                    <a class="nav-link text-white" asp-area="" asp-controller="BoardGames" asp-action="Index" style="margin-left:50px">Настільні ігри</a>
                </li>*@
                <li class="nav-item dropdown" >
                    <a class="nav-link text-white" asp-area="" asp-controller="Meeting" asp-action="Index" style="">Гуртки</a>
                </li>
                @if (User.IsInRole("user"))
                {
                    <li class="nav-item dropdown" style="margin-left:50px;">
                        <a class="nav-link text-white" asp-area="" asp-controller="Meeting" asp-action="Create">Створити гурток</a>
                    </li>
                }
                @if (User.IsInRole("admin"))
                   
                {
                    <li class="nav-item dropdown" style="margin-left:50px">
                        <a class="nav-link text-white" asp-area="" asp-controller="AdminUserManage" asp-action="Index">Всі користувачі</a>
                    </li>
                }


            </ul>
        </div>
    </nav>
</header>